services:

  mysql:
    image: mysql:8.0
    container_name: job-portal-mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [job-portal-network]

  redis:
    image: redis:7
    container_name: job-portal-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
    expose:
      - "6379"
    networks: [job-portal-network]

  job-portal-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE:-job-portal-backend:latest}
    container_name: job-portal-backend
    user: root
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    expose:
      - "8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks: [job-portal-network]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${FRONTEND_IMAGE:-job-portal-frontend:latest}
    container_name: job-portal-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # dùng file nginx.conf trong frontend làm default.conf
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # mount cert Let's Encrypt từ host vào container
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - job-portal-app
    networks: [job-portal-network]

networks:
  job-portal-network:
    driver: bridge

volumes:
  mysql_data:
